language: android

android:
        components:
                - platform-tools
                - build-tools-25.0.0
                - android-25
                - extra-android-m2repository
        licenses:
    - 'android-sdk-preview-license-.+'
    - 'android-sdk-license-.+'
    - 'google-gdk-license-.+'
script:
        - ./gradlew build
before_install:
        - chmod +x gradlew

jdk: oraclejdk8
