language: android
jdk: oraclejdk8
android:
  components:
    - platform-tools
    - build-tools-25.0.2
    - android-25
    - extra-android-m2repository
    
  licenses:
    - 'android-sdk-preview-license-52d11cd2'
    - 'android-sdk-license-.+'
    - 'google-gdk-license-.+'
    

before_script:
        echo y | android update sdk --no-ui --filter build-tools-25.0.2 ,android-25,extra-android-m2repository
script:
        - ./gradlew build
before_install:
        - chmod +x gradlew


